### ISSUE TITLE
Unfortunate name clash

### ISSUE THREAD

**Issue by skade** [robinmonjo/krgo#1]
`cargo` is the binary name for the package manager of the programming language Rust.

https://crates.io/

**Comment by pcn** [comment]
:+1:

**Comment by pcn** [comment]
Some other suggestions:
- drydock
- overhaul (like overhauling an engine where you take it apart outside of the car)
- longshore or longshoreman
- isthmus (for the vague connection to panama and transit passing through there)

**Comment by robinmonjo** [comment]
Hum, indeed. I'll keep it this way for now and change it when I found the time (and a new name).
@pcn thx for the suggestions !
@skade thx for pointing this out
